---
title: "STAT5703 HW1 Ex1"
author: "Chao Huang (ch3474), Wancheng Chen (wc2687), Chengchao Jin (cj2628)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=4.5, fig.height=3)
library("dplyr")
```

## Exercise 1.

#### Question 1.
To calculate $p^{th}$, we need to find $Q_D(p)$ such that $P(D\leq Q_D(p))=p$. Then, the previous function can be transformed to

$$\int_{0}^{Q_D(p)}\lambda e^{-\lambda D}dD=1-e^{-\lambda Q_D(p)}=p$$

So, from this equation, $Q_D(p)$ can be expressed by

$$Q_D(p)=-\frac{1}{\lambda}\ln{(1-p)}$$

#### Question 2.
From question(a), we already obtain the equation for $Q_D(p)$ which is $Q_D(p)=-\frac{1}{\lambda}\ln{(1-p)}$. Then, to find the MLE of $Q_D(p)$, we can find the MLE of $\lambda$ first and then replace $\lambda$ with its Maximum Likelihood Estimator $\hat\lambda^{MLE}$. $D_1,...,D_n$ are i.i.d. Exponential random variables with parameter $\lambda$, the log-likelihood function is

$$\ell (\lambda ;D_1,...,D_n)=n\ln{\lambda}-\sum_{i=1}^n\lambda D_i$$
The MLE $\hat\lambda^{MLE}$ is 

$$\hat\lambda^{MLE}=\frac{1}{\bar{D_n}}$$

and

$$Q_D(p)^{MLE}=-\frac{1}{\hat\lambda^{MLE}}\ln{(1-p)}=-\bar{D_n}\ln{(1-p)}$$

#### Question 3.
$D_1,...,D_n\overset{i.i.d.}{\sim}Exp(\lambda)$. Then the CLT tells us that
$$\sqrt{n}(\bar{D_n}-\mu)\xrightarrow[n\rightarrow \infty]{\mathcal{D}}\mathcal{N}(0,\sigma^2)$$
Hence, by Delta Method we can get,
$$\sqrt{n}(Q_D(p)+\frac{\ln{(1-p)}}{\lambda})\xrightarrow[n\rightarrow \infty]{\mathcal{D}}\mathcal{N}(0,\frac{(\ln{(1-p)})^2}{\lambda^2})$$
Then, for $approximate\ (1-\alpha)$-confidence interval,

$$L(D)=-\bar{D_n}\ln{(1-p)}-\frac{z_{1-\alpha/2}\times\ln{(1-p)}}{\lambda\sqrt{n}}$$

$$R(D)=-\bar{D_n}\ln{(1-p)}+\frac{z_{1-\alpha/2}\times\ln{(1-p)}}{\lambda\sqrt{n}}$$
So, the $approximate\ (1-\alpha)$-confidence interval for $Q_D(p)$ is $[-\bar{D_n}\ln{(1-p)}-\frac{z_{1-\alpha/2}\times\ln{(1-p)}}{\lambda\sqrt{n}},-\bar{D_n}\ln{(1-p)}+\frac{z_{1-\alpha/2}\times\ln{(1-p)}}{\lambda\sqrt{n}}]$

#### Question 4.
We know that if $D_1,...,D_n$ are independent exponential random variables with parameter $\lambda$, then
$$\lambda\bar{D_n}\sim \Gamma(n,n)$$
So, $\lambda\bar{D_n}$ is independent of the parameter $\lambda$, which means it is an exact pivot. 
To construct an exact confidence interval of the median, we can first transform $\lambda\bar{D_n}$ to $\chi^2$ distribution. Then,
$$2n\lambda\bar{D_n}\sim \chi^2_{2n}$$
Hence, for any $\alpha\in(0,1)$,
$$P(\chi^2_{1-\alpha/2,2n}<2n\lambda\bar{D_n}<\chi^2_{\alpha/2,2n})=1-\alpha$$
Since $Q_D(0.5)=-\bar{D_n}\ln{0.5}$, then

$$P(-\frac{\ln{0.5}\chi^2_{\alpha/2,2n}}{2n\lambda}<Q_D(0.5)<-\frac{\ln{0.5}\chi^2_{1-\alpha/2,2n}}{2n\lambda})=1-\alpha$$

Hence, the $(1-\alpha)$ exact confidence interval of the median is,
$$Q_D(0.5)\in[-\frac{\ln{0.5}\chi^2_{\alpha/2,2n}}{2n\lambda},-\frac{\ln{0.5}\chi^2_{1-\alpha/2,2n}}{2n\lambda}]$$